version: '3'
services:
  mydb:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: mydb
    restart: always # se o container para ele vai restartar sozinho 
    tty: true # permite entrar no container de maneira interativa
    volumes:
        - ./storage:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=mydatabase
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=mypassword
    networks:
        - my_net
    ports:
        - "3306:3306"

networks:
  my_net:
    driver: bridge